#result path
CHEMIN_RESULT /home/tomo/Projet_tomo/Tomo_result
#hologram path
CHEMIN_ACQUIS /ramdisk/ACQUIS
#config files path 
CHEMIN_CONFIG /ramdisk/ACQUIS

#utile seulement sur pc d'acquisition :
#only used on set up PC
CHEMIN_CONFIG_PC_ACQUIS /home/tomo/Projet_tomo/Tomo_config/
PC_ACQUIS 0

























































































